"""Add risk CRUD support and related model updates

Revision ID: 2ef4f7c63c9a
Revises: c9f84862cebe
Create Date: 2026-08-19 13:14:26.117903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef4f7c63c9a'
down_revision = 'c9f84862cebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_foreign_key('fk_assets_created_by_user_id_users', 'users', ['created_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_assets_tenant_id_tenants', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_foreign_key('fk_controls_tenant_id_tenants', 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key('fk_controls_created_by_user_id_users', 'users', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('corrective_actions', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_foreign_key('fk_corrective_actions_created_by_user_id_users', 'users', ['created_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_corrective_actions_tenant_id_tenants', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('file_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('mime_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('retention_policy',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('storage_provider',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_evidence_tenant_id_tenants', 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key('fk_evidence_uploaded_by_user_id_users', 'users', ['uploaded_by_user_id'], ['id'])

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_foreign_key('fk_findings_tenant_id_tenants', 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key('fk_findings_created_by_user_id_users', 'users', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_foreign_key('fk_policies_created_by_user_id_users', 'users', ['created_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_policies_tenant_id_tenants', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_foreign_key('fk_risks_tenant_id_tenants', 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key('fk_risks_created_by_user_id_users', 'users', ['created_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_risks_created_by_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_risks_tenant_id_tenants', type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_policies_tenant_id_tenants', type_='foreignkey')
        batch_op.drop_constraint('fk_policies_created_by_user_id_users', type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_findings_created_by_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_findings_tenant_id_tenants', type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_constraint('fk_evidence_uploaded_by_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_evidence_tenant_id_tenants', type_='foreignkey')
        batch_op.alter_column('storage_provider',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('retention_policy',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('mime_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('file_hash',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('corrective_actions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_corrective_actions_tenant_id_tenants', type_='foreignkey')
        batch_op.drop_constraint('fk_corrective_actions_created_by_user_id_users', type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.drop_constraint('fk_controls_created_by_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_controls_tenant_id_tenants', type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assets_tenant_id_tenants', type_='foreignkey')
        batch_op.drop_constraint('fk_assets_created_by_user_id_users', type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###
