"""Add awareness assignment uniqueness

Revision ID: 622ef7a38e4c
Revises: c3a48bf4c679
Create Date: 2026-08-21 22:32:23.781366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622ef7a38e4c'
down_revision = 'c3a48bf4c679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index('ix_assets_tenant_id', ['tenant_id'], unique=False)

    with op.batch_alter_table('awareness_assignments', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_awareness_assignment_user_campaign', ['tenant_id', 'campaign_id', 'user_id'])

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index('ix_policies_tenant_id', ['tenant_id'], unique=False)

    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index('ix_risks_status', ['status'], unique=False)
        batch_op.create_index('ix_risks_tenant_id', ['tenant_id'], unique=False)

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.create_index('ix_user_groups_tenant_id', ['tenant_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_photo_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.create_index('ix_users_email', ['email'], unique=False)
        batch_op.create_index('ix_users_role_id', ['role_id'], unique=False)
        batch_op.create_index('ix_users_tenant_id', ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_tenant_id')
        batch_op.drop_index('ix_users_role_id')
        batch_op.drop_index('ix_users_email')
        batch_op.alter_column('profile_photo_path',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_user_groups_tenant_id')

    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_index('ix_risks_tenant_id')
        batch_op.drop_index('ix_risks_status')

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index('ix_policies_tenant_id')

    with op.batch_alter_table('awareness_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_awareness_assignment_user_campaign', type_='unique')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index('ix_assets_tenant_id')

    # ### end Alembic commands ###
