"""Add awareness training group tracking

Revision ID: c3a48bf4c679
Revises: 2ef4f7c63c9a
Create Date: 2026-08-20 02:22:40.931439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a48bf4c679'
down_revision = '2ef4f7c63c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.alter_column('signature_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.alter_column('document_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('document_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('mime_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.alter_column('approval_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('approved_by_user_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('approved_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('signature_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('locked_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_risks_approved_by_user_id_users', 'users', ['approved_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_risks_approved_by_user_id_users', type_='foreignkey')
        batch_op.alter_column('locked_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('signature_hash',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('approved_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('approved_by_user_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('approval_status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.alter_column('mime_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('document_path',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('document_filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.alter_column('signature_hash',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
