"""Add Finding and CorrectiveAction models

Revision ID: ea55e5ce96a7
Revises: 8447cbf855d3
Create Date: 2026-08-15 02:46:09.714479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea55e5ce96a7'
down_revision = '8447cbf855d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('control_id', sa.Integer(), nullable=True),
    sa.Column('audit_name', sa.String(length=150), nullable=True),
    sa.Column('identified_date', sa.DateTime(), nullable=True),
    sa.Column('identified_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corrective_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corrective_actions')
    op.drop_table('findings')
    # ### end Alembic commands ###
